import Head from "next/head";
import * as React from "react";
import Image from "next/image";
import { ProductItem } from "../components/ProductItem";
import styles from "../styles/Home.module.css";
import store from "store";
import router, { useRouter } from "next/router";

export default function Home() {
  const number = "+551299999200";

  const products = [
    {
      image:
        "https://dourados.saofranciscoonline.com/media/catalog/product/cache/1/image/855x635/9df78eab33525d08d6e5fb8d27136e95/q/u/queijo-mussarela-fatiado-26307.jpg.jpg",
      name: "Queijo muçarela",
      info: "Peças de aproximadamente 1Kg",
      description:
        "Queijo do tipo muçarela, feito com leite da roça, ótimo para incrementar suas receitas. Vendido em peças de aproximadamente 1 Kg.",
      price: "34.90",
      priceType: "Kg",
    },
    {
      image:
        "https://dourados.saofranciscoonline.com/media/catalog/product/cache/1/image/855x635/9df78eab33525d08d6e5fb8d27136e95/q/u/queijo-mussarela-fatiado-26307.jpg.jpg",
      name: "Queijo Indiano",
      info: "Peças de aproximadamente 12Kg",
      description: "Queijo do tipo Indiano muito bom.",
      price: "14.90",
      priceType: "Kg",
    },
    {
      image:
        "https://dourados.saofranciscoonline.com/media/catalog/product/cache/1/image/855x635/9df78eab33525d08d6e5fb8d27136e95/q/u/queijo-mussarela-fatiado-26307.jpg.jpg",
      name: "Queijo Australiano",
      info: "Peças de aproximadamente 11Kg",
      description: "Queijo do tipo australiano é muito bom, comprem.",
      price: "24.90",
      priceType: "Kg",
    },
  ];

  const setRequest = (thisItem) => {
    thisItem.preventDefault();
    const items = document.querySelectorAll(".item");
    const itemsArray = [];

    items.forEach((item) => {
      const itemName = item.querySelector(".itemName").innerHTML;
      const itemDescription = item.querySelector(".itemDescription").innerHTML;
      const itemPrice = item.querySelector(".priceHidden").value;
      const itemQuantity = item.querySelector("#quantity").value;

      if (itemQuantity >= 1) {
        const itemData = {
          name: itemName,
          description: itemDescription,
          price: itemPrice,
          quantity: itemQuantity,
          total: parseFloat(
            parseInt(itemQuantity) * parseFloat(itemPrice)
          ).toFixed(2),
        };

        itemsArray.push(itemData);
      } else {
        return;
      }
    });

    if (itemsArray.length >= 1) {
      store.set("productList", JSON.stringify(itemsArray));
    }

    router.push("/finalizar");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Produtos | Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className={styles.banner}></div>
        <div className={styles.infos}>
          <div>
            {/* <div className={styles.logo}></div> */}
            <div>
              <h1>Empresa</h1>
              <p>Lorem ipsum dolor sit</p>
            </div>
          </div>

          <div>
            <strong>Horario de atendimento</strong>
            <p>Seg / Sex das 08h - 19h</p>
          </div>
          <div>
            <strong>Contato</strong>
            <p>
              <strong>Tel:</strong> XX-99999-9999
            </p>
          </div>
        </div>
      </header>
      <main className={styles.main}>
        <section className={styles.products}>
          <h2>Conheça nossos produtos</h2>

          <div className={styles.products__wrapper}>
            {products.map((product, id) => (
              <ProductItem
                key={id}
                image={`/api/imageproxy?url=${encodeURIComponent(
                  product.image
                )}`}
                name={product.name}
                info={product.info}
                description={product.description}
                priceValue={product.price}
                price={`R$ ${product.price} / ${product.priceType}`}
              />
            ))}
          </div>
        </section>

        <a href="#" onClick={setRequest} className={styles.btnWhatsApp}>
          Pedir no WhatsApp
        </a>
      </main>
    </div>
  );
}
